# Generated by Django 4.0.5 on 2022-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('story_id', models.IntegerField(unique=True)),
                ('href', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('story_title', models.CharField(max_length=255)),
                ('story_block', models.TextField()),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
    ]
