# Generated by Django 4.0.5 on 2022-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Short_tales', '0005_alter_category_options_alter_posts_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='story_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='id на сайте Pikabu'),
        ),
    ]
