# Generated by Django 4.0.5 on 2022-07-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Short_tales', '0006_alter_posts_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Short_tales.category', verbose_name='Категория'),
        ),
    ]
